#!/usr/bin/env php
<?php

if (
    (!$classLoader = file_exists(__DIR__.'/vendor/autoload.php')? require __DIR__.'/vendor/autoload.php':false) &&
    (!$classLoader = file_exists(__DIR__.'/../../autoload.php')? require __DIR__.'/../../autoload.php':false)
) {
    echo 'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -sS https://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL;
    exit(1);
}
include __DIR__.'/includes/init.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Finder\Finder;

$application = new Application();
$output = new ConsoleOutput();

if (!is_dir($dir = __DIR__ . '/src/Commands')) {
    return;
}

if (!class_exists('Symfony\Component\Finder\Finder')) {
    throw new \RuntimeException('You need the symfony/finder component to register bundle commands.');
}

$finder = new Finder();
$finder->files()->name('*Command.php')->in($dir);
foreach ($finder as $file) {
    // TODO use symfony function here
    $className = 'PrestaConsole\\Commands\\'.basename($file->getPath()).'\\'.$file->getBasename('.php');

    $r = new \ReflectionClass($className);
    if ($r->isSubclassOf('Symfony\\Component\\Console\\Command\\Command') && !$r->isAbstract() && !$r->getConstructor()->getNumberOfRequiredParameters()) {
        $application->add($r->newInstance());
    }
}

$application->run();